Bootstrap: docker
From: tensorflow/tensorflow:latest-gpu

%labels
	Maintainer cwieri39@calvin.edu

%post
	echo "Running : apt update"
	apt update
	echo "Running : apt install build-essential
	apt install -y build-essential
	echo "Running : apt install python-dev
	apt install -y python-dev
	echo "Installing : pip upgrade"
	pip install --upgrade pip
	echo "Installing : pip - keras"
	pip install scipy
	pip install six
	pip install pyyaml
	pip install h5py
	pip install numpy
	pip install Keras
