Bootstrap: docker
From: tensorflow/tensorflow:latest-gpu

%labels
	Maintainer cwieri39@calvin.edu

%post
	echo "Running : apt update"
	apt update
	echo "Running : apt install build-essential
	apt install -y build-essential
	echo "Running : apt install python-dev
	apt install -y python-dev
	echo "Installing : pip - keras"
	apt install -y python-scipy python-numpy python-six python-h5py python-yaml
	pip install -q Keras
